panda86_master_homepage:
    path:  /
    defaults: { _controller: Panda86MasterBundle:Dashboard:index }

panda86_master_d:
    path:  /dashboard
    defaults: { _controller: Panda86MasterBundle:Dashboard:dashboard }

panda86_master_c:
    path:  /client
    defaults: { _controller: Panda86MasterBundle:Dashboard:client }

panda86_master_r:
    path:  /reports
    defaults: { _controller: Panda86MasterBundle:Dashboard:reports }

panda86_master_r_a:
    path:  /reports/annual
    defaults: { _controller: Panda86MasterBundle:Dashboard:annual }

panda86_master_r_1:
    path:  /reports/quarterly
    defaults: { _controller: Panda86MasterBundle:Dashboard:quarter }

panda86_master_i:
    path:  /invoices
    defaults: { _controller: Panda86MasterBundle:Dashboard:invoices }
