parameters:
#    panda86_master.example.class: Panda86\MasterBundle\Example

services:
#    panda86_master.example:
#        class: %panda86_master.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
